### ISSUE TITLE
model problem

### ISSUE THREAD

**Issue by GaoPengGit** [facebookresearch/ov-seg#10]
How can I obtain a segment_ Anything's model

**Comment by Jeff-LiangF** [comment]
Thanks for your interest in OVSeg + SAM. 
Unfortunately, we have not updated SAM usage in this repo. We are planning to update those codes in the coming weeks.
An alternative solution is to use the [ovseg hugging face repo](https://huggingface.co/spaces/facebook/ov-seg) where you can easily find the checkpoints and codes. You can follow the environment setup as in this repo and run `python app.py` to execute.

Don't hesitate to reach out if you have further questions.
