### ISSUE TITLE
d2.engine.defaults]: No evaluator found. Use `DefaultTrainer.test(evaluators=)`, or implement its `build_evaluator` method.

### ISSUE THREAD

**Issue by Ako-r** [facebookresearch/ov-seg#13]

**Comment by Ako-r** [comment]
And how to evaluate the model on cityscapes?

**Comment by Jeff-LiangF** [comment]
Hi @Ako-r ,

We don't have the evaluation codes of cityscapes but I believe our model is able to do so. 

Some hints about how to write the cityscapes evaluator: 1. register the cityscapes dataset, like [pascal context](https://github.com/facebookresearch/ov-seg/blob/main/open_vocab_seg/data/datasets/register_pascal_context.py), you may need to define the class names, etc. 2. migrating the data [loading scripts of cityscapes from d2](https://github.com/facebookresearch/ov-seg/blob/main/open_vocab_seg/data/datasets/register_pascal_context.py). 

Btw, if you successfully evaluate on cityscapes, feel free to create a merge request. :)
