### ISSUE TITLE
Download data error!

### ISSUE THREAD

**Issue by shipengai** [facebookresearch/ov-seg#14]
when run ` gdown 1cycn5BpUjkSTIysEtxnAUFrgUEnQ5_pW `
it show `Access denied with the following error:

 	Too many users have viewed or downloaded this file recently. Please
	try accessing the file again later. If the file you are trying to
	access is particularly large or is shared with many people, it may
	take up to 24 hours to be able to view or download the file. If you
	still can't access a file after 24 hours, contact your domain
	administrator. 
`

**Comment by Jeff-LiangF** [comment]
Hi @shipengai ,

It is caused by too frequent downloads. If `gdown` doesn't work, you may want to directly download from [google drive](https://drive.google.com/drive/folders/1Yd1ZP_GZrJFm9XUroxkTWGkyvqu0V_Zv).
