### ISSUE TITLE
Where is visual prompt implemented

### ISSUE THREAD

**Issue by RuoyuChen10** [facebookresearch/ov-seg#2]
Thanks for your great work. Can you tell me where the visual prompt is implemented? Thank you very much.

**Comment by Jeff-LiangF** [comment]
Hi @RuoyuChen10 ,

Thanks for your interest in OVSeg! The inference code of the mask prompt can be found [here](https://github.com/facebookresearch/ov-seg/blob/main/third_party/CLIP/clip/model.py#L331). The training code is implemented with CLIP, which we are still working on cleaning. Stay tuned!

**Comment by Jeff-LiangF** [comment]
Hi @RuoyuChen10 ,

Please check out the training code of [mask prompt tuning](https://github.com/facebookresearch/ov-seg/tree/main/open_clip_training#mask-prompt-tuning). Feel free to reach out if you have any questions.
