### ISSUE TITLE
Reproducing the results of baseline w/ original CLIP

### ISSUE THREAD

**Issue by zifuwan** [facebookresearch/ov-seg#20]
Dear author,

Thanks for the great work! Could you tell me how many epochs are needed to train `baseline w/ original CLIP`? I've trained 2 epochs(10,000 iters), and the loss seems to have converged already. However, the testing results have a gap with your results( I have tested the weight you provided and the result was 29.6 on ADE-150 which was perfect. However, my result is only 18.0, and according to your paper, it should be 21.8). Could you help me out? 

Here are my training results and my training logs:
![06bc78c3cfd3fb8316f059e9668d746](https://github.com/facebookresearch/ov-seg/assets/77483744/4806e813-f2a7-48ed-b9aa-46a292fc7f86)
![image](https://github.com/facebookresearch/ov-seg/assets/77483744/289212b5-4d39-444b-a593-d16c9a4a258e)

Thanks.

**Comment by Jeff-LiangF** [comment]
Hi, thanks for your questions. I just checked my experiment records. 60k~120k training iters are usually good choices, so your model may be undertrained. Moreover, the performance is also sensitive to [`CLIP_ENSEMBLE_WEIGHT` ](https://github.com/facebookresearch/ov-seg/blob/main/configs/ovseg_R101c_vitB_bs32_120k.yaml#L53), you may also want to tune it a little bit to achieve the best results.

Thanks! I closed the issue. Feel free to reopen it if you have further questions.
