### ISSUE TITLE
SAM+Mask_adapted CLIP

### ISSUE THREAD

**Issue by weixu-x** [facebookresearch/ov-seg#21]
Hello, first of all, thanks for your very influential and interesting work sharing. I have tried the online demo and found it very interesting, but I did not find the code of this part. Are you willing to release the code of this part?

**Comment by Jeff-LiangF** [comment]
Hi, Thanks for you kind words. Very appreciate that! Are you talking about the SAM + CLIP code in [huggingface](https://huggingface.co/spaces/facebook/ov-seg)? Actually, you can git clone the code directly from huggingface. The pretrained models are also available in that repo. 

Let me know if you have further questions. Thank you!
