### ISSUE TITLE
demo.py

### ISSUE THREAD

**Issue by jixiaofeng123** [facebookresearch/ov-seg#22]
Hi, thanks for doing such interesting work, I am very interested in this, I ran it on an online demo with my own data and found the results very exciting. However, when running the demo.py file, I found that the result is not as good as the online demo, and I can't realize the arbitrary semantic segmentation without prompting, may I ask how to get the relevant code of the online demo. Looking forward to your reply!

**Comment by Jeff-LiangF** [comment]
Thanks for your interests. This is a very good finding. By default, [online demo](https://huggingface.co/spaces/facebook/ov-seg/tree/main) is using SAM as proposal generator which has finer grained and higher quality masks then MaskFormer proposal which is used in [demo.py](https://github.com/facebookresearch/ov-seg/blob/main/demo.py). So, it is expected you have better results with online demo.

If you are interested in online demo, you can directly git clone from [huggingface](https://huggingface.co/spaces/facebook/ov-seg/tree/main). The pretrained models are also available in that repo.

Thanks! Feel free to reopen the issue if you have further questions.
