### ISSUE TITLE
About train on other datasets

### ISSUE THREAD

**Issue by Zetianuser** [facebookresearch/ov-seg#26]
Hi, thanks for doing such interesting work.I would like to know how to train on my own datasets, I only have images and masks.Thank you.

**Comment by Jeff-LiangF** [comment]
Hi @Zetianuser ,

If you want to train a MaskFormer: Our code is based on detectorn2, please follow [the guidance here to prepare a custom dataset](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html).

If you want to fine-tune the CLIP: You first need to collect a image-text paired datasets. Then [follow the instruction to fine-tune the CLiP](https://github.com/facebookresearch/ov-seg/blob/main/open_clip_training/README.md)

**Comment by xinlong-yang** [comment]
> Hi @Zetianuser ,
> 
> If you want to train a MaskFormer: Our code is based on detectorn2, please follow [the guidance here to prepare a custom dataset](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html).
> 
> If you want to fine-tune the CLIP: You first need to collect a image-text paired datasets. Then [follow the instruction to fine-tune the CLiP](https://github.com/facebookresearch/ov-seg/blob/main/open_clip_training/README.md)

hi, could you please tell me how many GPUs are needed to train on our own datasets?
