### ISSUE TITLE
During the fine-tuning of CLIP, is the mask used generated by the previous segmentation model (with the original CLIP)?

### ISSUE THREAD

**Issue by vmmm123** [facebookresearch/ov-seg#28]
If the mask is not generated using the original CLIP in conjunction with a segmentation model, then it could raise questions about the zero-shot learning setting. This is because CLIP may have effectively been trained on specific classes it needs to identify, and it remains uncertain whether it would show similar effectiveness on classes that it has not encountered before.

**Comment by vmmm123** [comment]
Alternatively, if you have already used the fine-tuned CLIP model during the training of the previous segmentation model (with the original CLIP), it still wouldn't be considered zero-shot learning, because the model has been exposed to information about 'unknown classes.' These are my initial thoughts; can you help me understand if this perspective is correct?

**Comment by vmmm123** [comment]
sorry..I read your paper more carefully and understood. Great work!! Thank a lot!!

**Comment by bqm1111** [comment]
Could you elaborate more about your findings please? I have the same thought about the zero-shot learning setting here.
