### ISSUE TITLE
The CLIP ViT-B/16 model

### ISSUE THREAD

**Issue by gjc0824** [facebookresearch/ov-seg#3]
Hello, thank you for your amazing work! I want to know where can I get the version of ViT-B/16 backbone for CLIP and R101 for Maskformer. The ViT-L/14 is too big and it doesn't adapt my application. Thank you~

**Comment by Jeff-LiangF** [comment]
Hi @gjc0824,

Thanks for your interest in our work. We are working on releasing the R101 + ViT-B/16 OVSeg model. Stay tuned!

**Comment by ghost** [comment]
Hi @Jeff-LiangF , do you plan to work on ViT-B/32 for OVSeg model?

**Comment by Jeff-LiangF** [comment]
@gjc0824 , In any case that you are still working on R101c + ViT-B/16 ,please check out model (R101c + CLIP-ViT-B/16) [ovseg_R101c_vitB16_ft_mpt.pth](https://drive.google.com/file/d/1ZmeFMEkhuLqaWkhz4t4IlQ8YflrYja8q/view?usp=drive_link) (md5: <tt>c746f4</tt>) with. 

- Test on ADE20K-150
  ```bash
  python train_net.py --num-gpu 8 --eval-only --config-file configs/ovseg_R101c_vitB_bs32_120k.yaml MODEL.WEIGHTS #PATH_of_ovseg_R101c_vitB16_ft_mpt.pth DATASETS.TEST \(\"ade20k_sem_seg_val\",\) 
  ```

@ngthanhtin Unfortunately, our OVSeg didn't have a trained model with ViT-B/32. But you can use our [open clip training](https://github.com/facebookresearch/ov-seg/tree/main/open_clip_training#openclip-training-for-ovseg) to train your own ViT-B/32.

**Comment by XiongweiWu** [comment]
> @gjc0824 , In any case that you are still working on R101c + ViT-B/16 ,please check out model (R101c + CLIP-ViT-B/16) [ovseg_R101c_vitB16_ft_mpt.pth](https://drive.google.com/file/d/1ZmeFMEkhuLqaWkhz4t4IlQ8YflrYja8q/view?usp=drive_link) (md5: c746f4) with.
> 
> * Test on ADE20K-150
>   ```shell
>   python train_net.py --num-gpu 8 --eval-only --config-file configs/ovseg_R101c_vitB_bs32_120k.yaml MODEL.WEIGHTS #PATH_of_ovseg_R101c_vitB16_ft_mpt.pth DATASETS.TEST \(\"ade20k_sem_seg_val\",\) 
>   ```
> 
> @ngthanhtin Unfortunately, our OVSeg didn't have a trained model with ViT-B/32. But you can use our [open clip training](https://github.com/facebookresearch/ov-seg/tree/main/open_clip_training#openclip-training-for-ovseg) to train your own ViT-B/32.

@Jeff-LiangF Hi, I am using this lightweight CLIP model to re-train the segmenter, however, the error reports. Below list my command and error msg:

`python train_net.py --config-file configs/ovseg_R101c_vitB_bs32_120k.yaml --num-gpus 4 --dist-url tcp://127.0.0.1:50591  OUTPUT_DIR output/baseline_vit16/ MODEL.CLIP_ADAPTER.CLIP_MODEL_NAME ovseg_R101c_vitB16_ft_mpt.pth.pt`

error msg:
`  File "/xxxx/ov-seg/third_party/CLIP/clip/model.py", line 557, in build_model
    assert mask_prompt_depth == 0, 'ResNets do not support mask prompt tuning'
AssertionError: ResNets do not support mask prompt tuning`

Any suggestion?

**Comment by Jeff-LiangF** [comment]
Hello @XiongweiWu ,

The error is caused by the fact that `ovseg_R101c_vitB16_ft_mpt.pth.pt` contains MaskFormer ResNet + CLIP_ViTB. However, `MODEL.CLIP_ADAPTER.CLIP_MODEL_NAME` only requires CLIP_ViTB. Unfortunately, I didn't have the CLIP_ViTB in my hand.
There are two potential solutions
1) Extract the ViT-B from `ovseg_R101c_vitB16_ft_mpt.pth.pt`, you may refer to this [convertion tool.](https://github.com/facebookresearch/ov-seg/blob/main/tools/ovseg_replace_clip.py)
2) Use the provided ViT-L [here](https://drive.google.com/file/d/1zKI4RgM2QEMh1isGDgae3KJ4BtGp2Lzq/view)

Thanks, feel free to reach out if you have further questions.
