### ISSUE TITLE
The training process of ovseg

### ISSUE THREAD

**Issue by kellyiss** [facebookresearch/ov-seg#4]
Thanks for your amazing work!

Is the training of ovseg a two-stage pipeline? Where is the code for CLIP adaption?

Thanks

**Comment by Jeff-LiangF** [comment]
@kellyiss ,

Thanks for your interest in our work!

Yes, the training is two-stage. We are still working on cleaning the CLIP adaption code, please stay tuned!

**Comment by dongbo811** [comment]
This is a very interesting work, when will the complete code be released?

**Comment by algvr** [comment]
Thanks a lot for this project! Do you happen to have any updates on the CLIP adaptation code?
Thank you very much in advance!

**Comment by goncayilmaz** [comment]
Hello, it would be great if you could share the training of CLIP, is there any update on that?

**Comment by Jeff-LiangF** [comment]
Hi @kellyiss @dongbo811 @algvr @goncayilmaz ,

Sorry for the long delay, I have released the fine-tuning data of fine-tuning code in [open clip training](https://github.com/facebookresearch/ov-seg/tree/main/open_clip_training#openclip-training-for-ovseg). Feel free to check it out.
