### ISSUE TITLE
FREEZE_AT parameter in config

### ISSUE THREAD

**Issue by goncayilmaz** [facebookresearch/ov-seg#8]
Hello,

I was looking into the implementation of OVSeg and I cannot see where you used the cfg.BACKBONE.FREEZE_AT. I see that you initialize frozen_stages=-1 in SwinTransformer. Shouldnt it be initialized with this cfg.BACKBONE.FREEZE_AT value?

**Comment by Jeff-LiangF** [comment]
Hi @goncayilmaz, Thanks for pointing it out. We basically follow the setting FREEZE_AT==0 in [MaskFormer](https://github.com/facebookresearch/MaskFormer/blob/da3e60d85fdeedcb31476b5edd7d328826ce56cc/configs/ade20k-150/Base-ADE20K-150.yaml#L3). I checked out the [swin-transformer](https://github.com/facebookresearch/detectron2/blob/f75715ed3f8c994b0563406c31961669530fc0bb/detectron2/modeling/backbone/swin.py) in detectron2, looks like the arg cfg.BACKBONE.FREEZE_AT is not correctly fed into the swin-transformer initialization. I believe you are right, there is a bug. However, I conjecture (not verified) whether freezing or not would only have slight differences for the final performance. 

I close this issue. Feel free to reopen it if it doesn't solve your question.
